"""Aggregator — importing this module registers every model on `Base.metadata`.

Alembic's env.py imports from here so autogenerate / upgrade sees the full
schema. Each domain owns its own `models.py`; this file only re-exports.
"""

from __future__ import annotations

from .accounting.models import (
    Account,
    BankReceipt,
    DeferredTerm,
    EventJournalMap,
    JournalEntry,
    JournalLine,
    Period,
)
from .assistant.models import (
    AsstConversation,
    AsstMessage,
    IndexVersion,
    KbChunk,
    KbDocument,
    KnowledgeGap,
    RedactionLog,
    UsageCounter,
)
from .audit.models import AuditEvent
from .comm.models import Conversation, Message
from .commerce.models import (
    Cart,
    CartItem,
    Order,
    OrderLine,
    OrderSubOrder,
    PriceLock,
    Rfq,
    RfqOffer,
)
from .identity.models import (
    BackupCode,
    ChannelPartnerProfile,
    CustomerProfile,
    ImpersonationGrant,
    OtpRequest,
    Permission,
    Role,
    RolePermission,
    Session,
    SupplierProfile,
    UserPermission,
    TotpSecret,
    User,
    UserRole,
)
from .inventory.models import (
    Batch,
    Product,
    ProductCodingRequest,
    ProductVariant,
    ReorderAlert,
    Shortage,
    StockBalance,
    SupplierOffer,
    TransferOrder,
    TransferOrderLine,
)
from .logistics.models import (
    DeliveryShortage,
    DeliverySlot,
    Shipment,
    ShipmentLeg,
)
from .notifications.models import Notification
from .partners.models import (
    PartnerAccrual,
    PartnerDeposit,
    PartnerTerms,
)
from .pos.models import (
    PosBatch,
    PosSale,
    PosSaleLine,
)
from .production.models import (
    ManufacturingOrder,
    MOMaterial,
    MOStage,
)
from .sales.models import (
    CreditOverride,
    CreditTierSetting,
    CustomerCreditTier,
    CustomerDue,
    DeferredCustomerException,
    DeferredSetting,
    DeferredTierRate,
    EscalationEvent,
    PaymentApproval,
)

__all__ = [
    "Account",
    "AsstConversation",
    "AsstMessage",
    "AuditEvent",
    "BackupCode",
    "BankReceipt",
    "Batch",
    "Cart",
    "CartItem",
    "ChannelPartnerProfile",
    "Conversation",
    "CreditOverride",
    "CreditTierSetting",
    "CustomerCreditTier",
    "CustomerDue",
    "DeferredCustomerException",
    "DeferredSetting",
    "DeferredTierRate",
    "CustomerProfile",
    "DeferredTerm",
    "DeliveryShortage",
    "DeliverySlot",
    "EscalationEvent",
    "EventJournalMap",
    "IndexVersion",
    "KbChunk",
    "KbDocument",
    "KnowledgeGap",
    "RedactionLog",
    "UsageCounter",
    "ImpersonationGrant",
    "JournalEntry",
    "JournalLine",
    "MOMaterial",
    "MOStage",
    "ManufacturingOrder",
    "Message",
    "Notification",
    "Order",
    "OrderLine",
    "OrderSubOrder",
    "OtpRequest",
    "PartnerAccrual",
    "PartnerDeposit",
    "PartnerTerms",
    "PaymentApproval",
    "Period",
    "Permission",
    "PosBatch",
    "PosSale",
    "PosSaleLine",
    "PriceLock",
    "Product",
    "ProductCodingRequest",
    "ProductVariant",
    "ReorderAlert",
    "Rfq",
    "RfqOffer",
    "Role",
    "RolePermission",
    "Session",
    "Shipment",
    "ShipmentLeg",
    "Shortage",
    "StockBalance",
    "SupplierOffer",
    "SupplierProfile",
    "UserPermission",
    "TotpSecret",
    "TransferOrder",
    "TransferOrderLine",
    "User",
    "UserRole",
]
