/** @type {import('tailwindcss').Config}
 *  Theme ported verbatim from the Stitch export (white_moon design system).
 *  Font stacks extended to put the Arabic variant first so RTL copy renders
 *  in IBM Plex Sans Arabic and numerals/codes in JetBrains Mono.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c4c7c7',
        'surface-variant': '#e4e2e2',
        'on-secondary-fixed': '#1a1c1c',
        surface: '#fbf9f9',
        'on-surface-variant': '#444748',
        'on-surface': '#1b1c1c',
        'on-primary-container': '#858383',
        'primary-container': '#1c1b1b',
        'on-secondary': '#ffffff',
        'surface-tint': '#5f5e5e',
        'secondary-fixed': '#e2e2e2',
        secondary: '#5d5f5f',
        'inverse-surface': '#303031',
        'tertiary-container': '#1d1b1a',
        'surface-container': '#efeded',
        primary: '#000000',
        'on-primary-fixed': '#1c1b1b',
        'tertiary-fixed': '#e6e1df',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#474646',
        'on-background': '#1b1c1c',
        outline: '#747878',
        'inverse-primary': '#c8c6c5',
        'on-tertiary-fixed-variant': '#484645',
        'surface-container-high': '#e9e8e7',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-container': '#616363',
        'on-tertiary-fixed': '#1d1b1a',
        'inverse-on-surface': '#f2f0f0',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'secondary-container': '#dfe0e0',
        'on-error-container': '#93000a',
        'surface-dim': '#dbdad9',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#454747',
        'surface-bright': '#fbf9f9',
        'tertiary-fixed-dim': '#cac6c3',
        'primary-fixed-dim': '#c8c6c5',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#e5e2e1',
        'on-tertiary-container': '#868381',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e2e2',
        'surface-container-low': '#f5f3f3',
        background: '#fbf9f9',
        tertiary: '#000000',
        // Semantic signals (badges/pills only — per DESIGN.md)
        signal: '#0f6b3e',
        warning: '#a8650c',
        danger: '#b3261e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      spacing: {
        margin: '1.5rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        gutter: '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'small-medium': ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        body: ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        'body-medium': ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        'mono-medium': ['JetBrains Mono', 'monospace'],
        'mono-body': ['JetBrains Mono', 'monospace'],
        'headline-1': ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        display: ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        'headline-2': ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
        small: ['IBM Plex Sans Arabic', 'IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'small-medium': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        body: ['14px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '400' }],
        'body-medium': ['14px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '500' }],
        'mono-medium': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        'mono-body': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'headline-1': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '500' }],
        display: ['28px', { lineHeight: '36px', letterSpacing: '0', fontWeight: '500' }],
        'headline-2': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '500' }],
        small: ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
